  DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE/stage"
  DOCKER_IMAGE_TAG: "latest"
  CONTAINER_NAME: "dev-adminpanel-libebattle"
  PORT_MAPPING: "127.0.0.1:1030:80"

Build_Dev:
  stage: build
  only:
    - develop
  script:
    - echo "Building Docker image..."
    - cp $ENV_DEV .env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --no-cache -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker rmi -f $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  tags:
    - dev

Deploy_Dev:
  stage: deploy
  only:
    - develop
  script:
    - echo "Deploying Docker container..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - |
      if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo "Stopping existing container..."
        docker stop $CONTAINER_NAME
      fi
    - |
      if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
        echo "Removing existing container..."
        docker rm $CONTAINER_NAME
      fi
    - docker run -d --restart always --name $CONTAINER_NAME -p $PORT_MAPPING $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  tags:
    - dev-klap
