name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: Install dependencies
      run: npm install --force

    - name: Build Docker image
      run: |
        docker build -t personal-portfolio:latest .
        docker tag personal-portfolio:latest ${{ secrets.DOCKER_USERNAME }}/personal-portfolio:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/personal-portfolio:latest
