name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install dependencies
        run: npm install --force

      - name: Build React app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t hamidrdeveloper/personal-portfolio .

      - name: Push Docker image
        run: >
            docker login -u $secrets.DOCKER_USERNAME -p $secrets.DOCKER_PASSWORD $CI_REGISTRY &&
            docker push hamidrdeveloper/personal-portfolio

      - name: Deploy to the server (adjust this step based on your deployment method)
        run: |
            ssh your-server-user@your-server-ip "docker pull hamidrdeveloper/personal-portfolio:latest && docker-compose up -d"
