name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
    - name: Build Docker image
      run: |
        docker build -t my-react-app .
        docker tag my-react-app:latest my-docker-account/my-react-app:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push my-docker-account/my-react-app:latest
